### ISSUE TITLE
Add `language\golang` GitHub Issue label to GitHub issue templates for features and bugs

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery-nighthawk#15]
#### Current Behavior
This https://github.com/meshery/meshery-nighthawk/blob/master/.github/ISSUE_TEMPLATE/feature_request.md template and the bugs template both need to be updated to have the `language/golang` label by default.

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by RyanbowZ** [comment]
Hello, I am a newcomer here, could you please assign this issue to me? Thanks!

**Comment by leecalcote** [comment]
Sounds great, Yuanlong. 👍

**Comment by leecalcote** [comment]
Thank you, @RyanbowZ 👏
