### ISSUE TITLE
[Chore] Refresh adapter boilerplate with latest

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery-nighthawk#17]
### Current Behavior
This repo is created quite some time ago and contains our antiquated content. Please remove any reference to OAM and replace with Models. 

### Implementation
Please refresh from [Meshery Adapter for Istio workflows](https://github.com/meshery/meshery-istio/tree/master/.github) as appropriate.

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment]
@gyohuangxin, FYI, @MUzairS15 made progress on the rewrite and getting this adapter to a functional state. PR for review forthcoming.

**Comment by gyohuangxin** [comment]
@MUzairS15 Do we have completed the initial work for this adapter?

**Comment by MUzairS15** [comment]
Yes https://github.com/meshery/meshery-nighthawk/pull/31

**Comment by gyohuangxin** [comment]
@MUzairS15 Thanks!
