### ISSUE TITLE
[Docs] Readme: Broken Images

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery-nighthawk#28]
#### Current Behavior
Images in the readme are in need of having their links fixed.

#### Expected Behavior
No broken image links in [readme](https://github.com/meshery/meshery-nighthawk/edit/master/README.md).

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 📝 [Meshery Adapters Spreadsheet](https://docs.google.com/spreadsheets/d/1rGGpSXC68iDJzNRU-qZIRQsZUwkt1qLFg7JCs4pfvbU/edit?usp=sharing)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by Aayush987** [comment]
Hello, i can work on this issue. Please assign it to me.

**Comment by aliasimkazmi** [comment]
I'd like to work with this as well. I can collaborate with @Aayush987. Looking forward to first issue here.

**Comment by ranjeetxsingh** [comment]
@leecalcote  the issue still persist, I looked into it and found that the img src url are actually specified to look into wrong directory. while the images are present under 'asset' folder, in the readme file they are being searched in 'img' folder which does not exist. I am glad to help on this issue.

**Comment by leecalcote** [comment]
Gosh, I missed these messages previously. My apologies.

**Comment by ranjeetxsingh** [comment]
@leecalcote review needed
